# Metadata

[profile.default]
# Project structure
libs = ["node_modules/", "lib/"] 
out = 'out' # Output directory for compiled artifacts
script = 'script' # Script directory
src = 'src' # Source directory
test = 'test' # Test directory

# Remappings
auto_detect_remappings = true # Automatically detect remappings in 'libs' directories

offline = false # Disable downloading missing solc versions
optimizer = true # Enable the optimizer
optimizer_runs = 200 # Number of optimizer runs
solc = '0.8.28' # Specific Solidity compiler version
