name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Node.js directly from .nvmrc
      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: contracts/.nvmrc

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.15.4"

      # Install Node dependencies via pnpm
      - name: Install Node Dependencies
        working-directory: contracts
        run: pnpm install

      # Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Show Forge version
      - name: Show Forge version
        working-directory: contracts
        run: forge --version

      # Run Forge formatting check
      - name: Run Forge fmt
        working-directory: contracts
        run: forge fmt --check

      # Run Forge build
      - name: Run Forge build
        working-directory: contracts
        run: forge build --sizes

      # Run Forge tests
      - name: Run Forge tests
        working-directory: contracts
        run: forge test -vvv
